### ISSUE TITLE
Selecting by name is not found

### ISSUE THREAD

**Issue by musm** [mietzen/juliamono-nerd-font#1]
I'm attempting to use this font by:

```
  "editor.fontFamily": "JuliaMono Nerd Font Mono",

```

for example in VS code. But the font name is not found here.

**Comment by cormullion** [comment]
Perhaps try:

<img width="1058" alt="Screenshot 2023-11-11 at 12 26 58" src="https://github.com/mietzen/juliamono-nerd-font/assets/52289/7035b3a2-d8b8-44ef-b8fc-82d4799c6608">

**Comment by mietzen** [comment]
Put it in quotes:
![image](https://github.com/mietzen/juliamono-nerd-font/assets/31704359/83ebe00b-15e6-40b3-8313-0607db4823ac)

`"editor.fontFamily": "'JuliaMono Nerd Font Mono'"`

Edit: I'm on MacOS

**Comment by musm** [comment]
Interesting apparently if there is more than one space in the font name, it **must** be enclosed by single quotes. If it's a single space in the name, then no single quotes are required....
