### ISSUE TITLE
The julia _logo_ in the REPL splash screen does not render as nicely as with the standard JuliaMono

### ISSUE THREAD

**Issue by disberd** [mietzen/juliamono-nerd-font#10]
Hi @mietzen, thanks a lot for this nerd font addition.

I noticed that the julia logo in the REPL renders differently for me (pwsh on windows terminal) compared the standard juliamono, specifically for the julia _dots_.

Here are some pics

JuliaMono Nerd Font:
![image](https://github.com/user-attachments/assets/d8c1a843-0097-4de5-be23-7a9f45812fcf)

JuliMono (non Nerd):
![image](https://github.com/user-attachments/assets/22cf58f8-3959-48eb-8a6b-fdf3d6aa96d1)

MesloLGM Nerd Font (another Nerd font I was using):
![image](https://github.com/user-attachments/assets/052ab361-acab-44bf-a221-84e029207299)

Do you know if this expected or if there is a way to customize this?

**Comment by mietzen** [comment]
It is a [stylistic set](https://juliamono.netlify.app/#stylistic_sets) you need to activate, here an example for iTerm2 on macOS:

![image](https://github.com/user-attachments/assets/ace135ae-a784-47e1-a797-abd93cf28a7c)

Edit: Wrong image
